from __future__ import annotations

WINDOW_TITLE = "Gomoji"
SCREEN_WIDTH = 256
SCREEN_HEIGHT = 192
FPS = 30

BACKGROUND_COLOR = 0
TEXT_COLOR = 7
ACCENT_COLOR = 10
SHADOW_COLOR = 1
DEBUG_COLOR = 13
GRID_COLOR = 5
ACTIVE_COLOR = 11
LOCKED_COLOR = 3

PLACEHOLDER_WORDS = ("GOMJI", "KOTBA", "PYXEL", "MOJIQ")
