from __future__ import annotations

WINDOW_TITLE = "Gomoji"
SCREEN_WIDTH = 256
SCREEN_HEIGHT = 192
FPS = 30

BACKGROUND_COLOR = 0
TEXT_COLOR = 7
ACCENT_COLOR = 10
SHADOW_COLOR = 1
DEBUG_COLOR = 13

PLACEHOLDER_MOTIFS = ("GO", "MO", "JI")
