from __future__ import annotations

WINDOW_TITLE = "ごもじンゴ"
SCREEN_WIDTH = 396
SCREEN_HEIGHT = 696
FPS = 30
FONT_PATH = "assets/umplus_j12r.bdf"

BACKGROUND_COLOR = 0
TEXT_COLOR = 7
ACCENT_COLOR = 10
SHADOW_COLOR = 1
DEBUG_COLOR = 13
GRID_COLOR = 5
ACTIVE_COLOR = 11
LOCKED_COLOR = 3
